### ISSUE TITLE
Need highcharts/highcharts-more

### ISSUE THREAD

**Issue by justin808** [soldair/highcharts-browserify#12]
What's the best way to get highcharts/highcharts-more with this project?

I just ran into an issue where the highcharts-more file got out of sync, and that was a huge time waste.

I could fork this project and provide a PR.

I'd also like to get the code unminified. Any recommendations on that?

**Comment by soldair** [comment]
if you work on a pr that would be fine. I'm not sure what the issue with un-minified was perhaps another contributor can answer?
