### ISSUE TITLE
Initialize Higharts error: setting a property that has only a getter

### ISSUE THREAD

**Issue by axelSok** [soldair/highcharts-browserify#22]
good day
The error occurs during the initialization of the adapter (window = window || {}; // setting a property that has only a getter). 
Reproduced in FF and IE9

**Comment by soldair** [comment]
thanks for the report! =)

It looks like that code is right here 
https://github.com/soldair/highcharts-browserify/blob/master/templates/highcharts.txt

it looks like that line has no point. In node this throws. And everywhere else it's used window is defined. 
```js
> window = window||{}
ReferenceError: window is not defined
```

**Comment by soldair** [comment]
@achingbrain is there something I'm missing or should we just get rid of it?

**Comment by achingbrain** [comment]
No, that looks like it should come out.  Oops, sorry.

**Comment by soldair** [comment]
published as 2.0.1

**Comment by achingbrain** [comment]
It should probably come out of the other templates too:

https://github.com/soldair/highcharts-browserify/search?utf8=%E2%9C%93&q=filename%3A*.txt+window+%3D&type=Code

**Comment by soldair** [comment]
=) got them 2.0.2
