### ISSUE TITLE
Is it possible to get an unminified browser build?

### ISSUE THREAD

**Issue by blazzy** [soldair/highcharts-browserify#5]
Most people using browserify will have their own build pipeline to minify code as they see fit.

An unminified version makes debugging easier. Especially when we can use it to generate source maps for our production minified build.

**Comment by soldair** [comment]
highcharts uses closure compiler to assemble it's source so its tricky getting a complete unminfied build.

let me know if you figure it out. you should add it to the project.

**Comment by KenanY** [comment]
I was about to close this as un-actionable, but I was discovered that http://code.highcharts.com/ has unminified sources as well (`*.src.js`). Also HighCharts is open-source https://github.com/highslide-software/highcharts.com :)

So, I think this can totally be done!
