### ISSUE TITLE
Version Numbering

### ISSUE THREAD

**Issue by oliverbenns** [soldair/highcharts-browserify#6]
There seems to be an issue with the semver convention being used.

When npm installing, it gives:
```
"highcharts-browserify": "^0.1.3-4.0.4",
```

This isn't really clear what this means and I think this really needs addressing with correct semver points.

**Comment by soldair** [comment]
it may seem unclear but those people who track a specific version of highcharts can use this prerelease fragment to identify the nested highcharts version. This is borderline proper use of semver per semver.org but understand your icky feeling.

the thing is.. we have had to make api changes to how we export highcharts which wouldn't have been possible without breaking a user's project without a proper semver for highcharts-browserify itself. 
As convenience to users who requested it i add the real highcharts version in the prerelease fragment of the package version string. Again this is fully semver compliant but it should probably be added to the build metadata section to be more clear . x.y.Z-hc+hcversionhere 

pull requests to update highcharts and version conventions accepted. I don't use this much any more so help from people who care would be awesome. 

For all my projects i use the open opensource philosophy. So contribute and become a contributor! =)
https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md

http://semver.org/ for more info on adding crap to your versions.

**Comment by StoneCypher** [comment]
hi, please don't use invalid semver, it breaks a bunch of unrelated stuff

**Comment by StoneCypher** [comment]
hi, please don't use exotic semver.  it breaks npm, by far semver's dominant consumer

yes, rule 9 allows this, but real world tooling does not

**Comment by StoneCypher** [comment]
it's actually not possible to install highest version right now if you're using npm `2.12`, even though it used to work in `2.8`

try installing and setting your version to `*` instead of pinning

this is significantly broken

**Comment by StoneCypher** [comment]
```
npm ERR! notarget No compatible version found: highcharts-browserify@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0-3.0.10","0.0.1-3.0.10","0.1.1-4.0.3","0.1.2-4.0.4","0.1.3-4.0.4","0.1.4-4.0.4"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '(censored)'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/(censored)/npm-debug.log
```

**Comment by soldair** [comment]
prs welcome. I don't use this these days and am happy to have more
maintainers!
