### ISSUE TITLE
I get error in "d.reflow !== !1 && N(f, "load", ", N is undefined

### ISSUE THREAD

**Issue by totty90** [soldair/highcharts-browserify#7]
I've done this and copy pasted an example
    
    var Highcharts = require('highcharts-browserify');

    var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'body',
            // type: 'bar',
        },
        title: {
            text: 'Monthly Average Temperature',
            x: -20 //center
        },
        subtitle: {
            text: 'Source: WorldClimate.com',
            x: -20
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
            title: {
                text: 'Temperature (°C)'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: '°C'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Tokyo',
            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
        }, {
            name: 'New York',
            data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
        }, {
            name: 'Berlin',
            data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
        }, {
            name: 'London',
            data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
        }]
        // series: [realStocks]
    })

And I'm getting this annoying error. I use webpack.

**Comment by soldair** [comment]
not sure why this is. i spent a good amount of time trying to figure it out and trying to upgrade high charts to see if it went away but had issues just getting the new highcharts to work.

let me know if you figure it out

**Comment by totty90** [comment]
Yes, create a module to load the adapter, put the adapter in the window variable specifically. Then it works. 

The highcharts guy makes life hard for module loaders because doesn't lookup for the adapter like this `Adapter` but specify the window like this `window.Adapter`.
