### ISSUE TITLE
UTF16 bullet character in highcharts.js is being truncated to UTF8

### ISSUE THREAD

**Issue by jamesandres** [soldair/highcharts-browserify#8]
I think your nodejs script for building the wrapped highcharts scripts is causing this behaviour.

There is a `●` character in the original highcharts.js file from http://www.highcharts.com/. This character is being chopped to become `â—`.

These bullets are used in default highcharts pointFormat.

Thanks,

**Comment by soldair** [comment]
interesting. thanks for pointing this out.

**Comment by KenanY** [comment]
Looks like this was introduced in https://github.com/soldair/highcharts-browserify/commit/fcd3e9ad1afd76493ec44a7d710513fe1e8fff9e#diff-a2e68df398b2ca7220954871d1b1f2ca (hard diff to read though). The build process does not write to this file so, I don't know, maybe a text editor ruined it? Also, AFAICT, `●` (U+25CF BLACK CIRCLE) is also [part of](https://codepoints.net/U+25CF) UTF8.

**Comment by jamesandres** [comment]
If you search (in your browser) for `●` in either https://github.com/soldair/highcharts-browserify/blob/fcd3e9ad1afd76493ec44a7d710513fe1e8fff9e/highcharts.js or https://github.com/soldair/highcharts-browserify/blob/master/highcharts.js you won't find it but will find several occurrences of `â—`. The error appears to be committed to your repo.

I'm not what the exact cause is, but the black circle in the original highcharts.js file (from highcharts.com) appears to be 4 bytes long. The UTF16 was a guess on my part :)

**Comment by KenanY** [comment]
@jamesandres 

> you won't find it

Exactly, because https://github.com/soldair/highcharts-browserify/commit/fcd3e9ad1afd76493ec44a7d710513fe1e8fff9e removed it. You can see that it is present in the [parent commit](https://github.com/soldair/highcharts-browserify/blob/5b7b0cc0aceadf1f3f6ff0d31dd66c741ef21d74/highcharts.js). AFAICT the solution is to just manually put it back (i.e. revert the change to `highcharts.js` that was introduced in https://github.com/soldair/highcharts-browserify/commit/fcd3e9ad1afd76493ec44a7d710513fe1e8fff9e).

**Comment by jamesandres** [comment]
Ah sorry @KenanY I didn't notice you were a different commenter from @soldair.

I think you are right with the text editor hypothesis. Yes, it needs a revert. I think we are saying the same thing :)

**Comment by soldair** [comment]
ill publish this to npm soon. please ping again if i forget

**Comment by KenanY** [comment]
@soldair ping :)

**Comment by soldair** [comment]
time to push it to npm?

**Comment by jamesandres** [comment]
Yes please @soldair :)

**Comment by soldair** [comment]
ok. published. 0.1.4-4.0.4
